#!/usr/bin/python

rule make_avinput:
    input:
        vcf = 'info_renamed_vcf_chunks/{chunk}.vcf',
        av = 'av_warning_variants/{chunk}.avinput'
    output:
        'avinput/{chunk}.avinput'
    params:
        script = 'perl /usr/local/apps/ANNOVAR/2017-07-16/convert2annovar.pl'
    run:
        shell('{params.script} --format vcf4old --includeinfo {input.vcf} --outfile {output}')
        with open(input.av) as f, open(output[0], 'a') as out:
            a = f.read()
            out.write(a)
            
