#!/usr/bin/python

rule annotate_vcf_chunk:
    input:
        vcf = 'sorted_min_rep_vcf_chunks/{chunk}.vcf',
        av = 'avinput/{chunk}.avinput',
        intervar = 'InterVar_chunks/{chunk}.InterVarOutput.hg19_multianno.txt.intervar',
        tabVcf = vcf
    output:
        'annotated_vcf_chunk/{chunk}.vcf'
    params:
        module = 'module load python/2.7'
    shell:
        '{params.module};python scripts/annotateVcf.py {input.vcf} {output} {input.av} {input.intervar} {input.tabVcf}'


rule cat_annotated_vcf_chunks:
    input:
        expand('annotated_vcf_chunk/{chunk}.vcf', chunk = CHUNKS)
    output:
        'variants_InterVar_annotated.vcf'
    run:
        with open(output[0], 'w') as out:
            with open('annotated_vcf_chunk/' + CHUNKS[0] + '.vcf') as f:
                for line in f:
                    out.write(line)
            for chunk in CHUNKS[1:]:
                with open('annotated_vcf_chunk/' + chunk + '.vcf') as f:
                    line = f.readline()
                    while line != '' and line[0] == '#':
                        line = f.readline()
                    while line != '':
                        out.write(line)
                        line = f.readline()


rule bgzip_annotated_vcf:
    input:
        'variants_InterVar_annotated.vcf'
    output:
        'variants_InterVar_annotated.vcf.gz'
    params:
        module = 'module load tabix/0.2.6'
    shell:
        '{params.module};bgzip {input}'

rule tabix_annotated_vcf:
    input:
        'variants_InterVar_annotated.vcf.gz'
    output:
        'variants_InterVar_annotated.vcf.gz.tbi'
    params:
        module = 'module load tabix/0.2.6'
    shell:
        '{params.module};tabix -p vcf {input}'

