#!/usr/bin/python

rule make_avinput:
    input:
        'info_renamed_vcf_chunks/{chunk}.vcf'
    output:
        'avinput/{chunk}.avinput'
    params:
        script = 'perl /usr/local/apps/ANNOVAR/2017-07-16/convert2annovar.pl'
    shell:
        '{params.script} --format vcf4old --includeinfo {input} --outfile {output}'
