#!/usr/bin/python

rule run_intervar:
    input:
        'avinput/{chunk}.avinput'
    output:
        'InterVar_chunks/{chunk}.InterVarOutput.hg19_multianno.txt.intervar'
    params:
        out = 'InterVar_chunks/{chunk}.InterVarOutput',
        module = 'module load python/2.7;module load InterVar/2.0'
    shell:
        '{params.module};InterVar -i {input} -d $ANNOVAR_DATA/hg19 -o {params.out}'


rule sort_intervar:
    input:
        'InterVar_chunks/{chunk}.InterVarOutput.hg19_multianno.txt.intervar'
    output:
        'sorted_interVar_chunks/{chunk}.bed'
    params:
        module = 'module load bedtools/2.27.1'
    shell:
        '{params.module}; bedtools sort -header -i {input} > {output}'


rule cat_intervar:
    input:
        expand('sorted_interVar_chunks/{chunk}.bed', chunk = CHUNKS)
    output:
        'InterVar_bed/build.intervar.bed'
    run:
        with open(output[0], 'w') as out:
            with open('sorted_interVar_chunks/' + CHUNKS[0] + '.bed') as f:
                for line in f:
                    out.write(line)
            for chunk in CHUNKS[1:]:
                with open('sorted_interVar_chunks/' + chunk + '.bed') as f:
                    head = f.readline()
                    line = f.readline()
                    while line != '':
                        out.write(line)
                        line = f.readline()

rule bgzip_bed:
    input:
        'InterVar_bed/build.intervar.bed'
    output:
        'InterVar_bed/build.intervar.bed.gz'
    params:
        module = 'module load tabix/0.2.6'
    shell:
        '{params.module};bgzip {input}'


rule tabix_bed:
    input:
        'InterVar_bed/build.intervar.bed.gz'
    output:
        'InterVar_bed/build.intervar.bed.gz.tbi'
    params:
        module = 'module load tabix/0.2.6'
    shell:
        '{params.module};tabix -p bed -S 1 {input}'

